# -*- coding: utf-8 -*-
u"""
Is the thing we ship the thing we built? RUNBOOK step 4a.

===========================================================================
🚨 THE DATA FILES FAIL **SILENTLY**, AND THAT IS WHY THIS FILE EXISTS
===========================================================================

`naming/alias.py::load()` fails OPEN, deliberately and correctly —
`00-INDEX.md` Rule 1: *the alias table is an accelerator, never a dependency.*
A missing table returns an empty `Table()` and raises nothing, because
refusing to run would cost a user everything for a file one command
regenerates.

⛔ **That is exactly the wrong failure mode for a PACKAGING mistake.** A wheel
built without `package-data` installs cleanly, imports cleanly, runs cleanly,
and is quietly much worse at the one thing that makes cross-script pairing
work at all — `Hell Mode` meeting `ヘルモード ~やり込み好きの…~`.

⭐ **MEASURED, so the number is not an argument:**

    settled by name, table OFF   180 / 350   51.4%
    settled by name, table ON    280 / 350   80.0%

**28.6 points of pairing quality, lost with no error anywhere.** No comment in
`pyproject.toml` would have caught that; a check that opens the file does.

⚠ These run against the IMPORTED package, wherever it came from — a source
tree, a wheel, a `pip install -e`. That is the point: the question is not
*"is the file in the repository"* but *"is it in the thing that got
installed."*
"""
import gzip
import io
import json
import os
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import tsubasa                                               # noqa: E402
from tsubasa.naming import alias as ALIAS                    # noqa: E402
from tsubasa.naming import decoration as DECO                # noqa: E402

#: ⚠ FLOORS, not exact counts. The table is regenerated by
#: `python -m tsubasa.dev alias --harvest`, so it grows; pinning the exact
#: figure would turn every legitimate refresh into a failing check.
#: ⛔ They are high enough that a TRUNCATED file fails, which is the other way
#: this goes wrong — a partial copy is not an empty one.
MIN_ALIAS_ROWS = 100000
MIN_ALIAS_BYTES = 1000000
MIN_DECORATION_TOKENS = 100


def _data_dir():
    return os.path.join(os.path.dirname(os.path.abspath(tsubasa.__file__)),
                        u"data")


def test_the_package_carries_its_data_directory():
    u"""⛔ The first thing a bad wheel loses."""
    where = _data_dir()
    assert os.path.isdir(where), (
        u"no data/ inside the installed package at %s — the wheel was built "
        u"without package-data, and NOTHING will raise at runtime" % where)


def test_the_alias_table_is_present_and_not_truncated():
    u"""🚨 4.1 MB, 221,258 entries when this was written. Absent OR truncated
    both degrade silently; only a size floor catches the second."""
    path = os.path.join(_data_dir(), u"aliases.tsv.gz")
    assert os.path.isfile(path), u"aliases.tsv.gz is not in the package"
    size = os.path.getsize(path)
    assert size >= MIN_ALIAS_BYTES, (
        u"aliases.tsv.gz is %d bytes — a truncated or placeholder file. "
        u"The real table is over 4 MB." % size)

    with gzip.open(path, u"rt", encoding=u"utf-8") as fh:
        first = fh.readline()
    assert first.lstrip().startswith(u"{"), (
        u"the table does not start with its metadata line: %r" % first[:60])


def test_the_alias_table_actually_LOADS_with_real_entries():
    u"""⭐ THE CHECK THAT MATTERS. The file being present is not the claim;
    the claim is that the loader returns a populated table.

    ⛔ `load()` returns an empty `Table()` for a missing, corrupt or
    unreadable file **without raising** — so asserting `load()` succeeded
    proves nothing at all. The entry count is the only honest witness.
    """
    table = ALIAS.load()
    assert len(table) >= MIN_ALIAS_ROWS, (
        u"the alias table loaded %d entries. Under %d means it is missing, "
        u"truncated or unreadable — and NOTHING raises when that happens. "
        u"Measured cost: settled-by-name falls 80.0%% to 51.4%%."
        % (len(table), MIN_ALIAS_ROWS))


def test_an_ABSENT_table_is_survivable_but_measurably_worse():
    u"""⚠ THE OTHER HALF OF THE SAME CLAIM, and it has to be asserted too.

    The fail-open behaviour is a DESIGN DECISION, not an accident, so a check
    that only demanded the table be present would be a gate stricter than the
    decision the project already made (`doctrine/evidence`). Both are true:
    absent is survivable, AND absent is worse.
    """
    empty = ALIAS.load(path=os.path.join(_data_dir(), u"no-such-table.tsv.gz"))
    assert len(empty) == 0
    assert len(ALIAS.load()) > len(empty)


def test_the_decoration_vocabulary_is_present_and_populated():
    path = os.path.join(_data_dir(), u"decoration.json")
    assert os.path.isfile(path), u"decoration.json is not in the package"
    with io.open(path, u"r", encoding=u"utf-8") as fh:
        loaded = json.load(fh)
    assert len(loaded.get(u"tokens", ())) >= MIN_DECORATION_TOKENS, (
        u"%d decoration tokens — the vocabulary is empty or truncated"
        % len(loaded.get(u"tokens", ())))
    # ⭐ And it reaches the code that uses it, not just the disk. The file
    # being on disk and the loader returning a populated vocabulary are two
    # different claims, and only the second one is the product.
    assert len(DECO.load()) >= MIN_DECORATION_TOKENS


def test_the_library_imports_with_numpy_ALONE():
    u"""🚨 THE DEPENDENCY CLAIM, ENFORCED RATHER THAN DOCUMENTED.

    `pyproject.toml` declares exactly one hard dependency, and every other
    third-party import in the package is lazy and guarded. That is a promise
    to anyone embedding this, and a promise nothing checks is a comment.

    ⛔ A bare `import tsubasa` in a fresh process is not enough — the lazy
    imports live inside functions, so an accidental top-level `import guessit`
    somewhere would only show up when that module is first touched. This
    blocks them at the meta path and re-imports the package from scratch.
    """
    blocked = {u"anitopy", u"guessit", u"send2trash", u"onnxruntime",
               u"tkinterdnd2", u"PIL", u"scipy", u"pandas"}

    class Block(object):
        def find_module(self, name, path=None):
            return self if name.split(u".")[0] in blocked else None

        def load_module(self, name):
            raise ImportError(u"%s is blocked: it may not be a hard "
                              u"dependency of the library" % name)

    saved = {k: v for k, v in sys.modules.items()
             if k == u"tsubasa" or k.startswith(u"tsubasa.")}
    for key in list(saved):
        del sys.modules[key]
    sys.meta_path.insert(0, Block())
    try:
        import tsubasa as fresh
        import tsubasa.pipeline                               # noqa: F401
        import tsubasa.api                                    # noqa: F401
        import tsubasa.cli                                    # noqa: F401
        assert callable(fresh.scan) and callable(fresh.sync)
    finally:
        sys.meta_path.pop(0)
        sys.modules.update(saved)


def test_the_gui_is_NOT_reachable_from_the_library_import():
    u"""⛔ `tkinter` is not a hard dependency and a headless host must be able
    to import the library. Only `tsubasa.gui.app` may touch it."""
    saved = {k: v for k, v in sys.modules.items()
             if k == u"tsubasa" or k.startswith(u"tsubasa.")}
    for key in list(saved):
        del sys.modules[key]
    try:
        import tsubasa                                        # noqa: F811
        import tsubasa.pipeline                                # noqa: F401
        assert u"tkinter" not in sys.modules, (
            u"importing the library pulled in tkinter — a headless install "
            u"cannot use it")
    finally:
        sys.modules.update(saved)


def test_the_version_is_not_a_placeholder():
    u"""⚠ `0.0.0+dev` is what an unpackaged tree reports. A published artifact
    saying that cannot be told apart from any other build of it, which breaks
    `10-deployment.md`'s *the live artifact's version equals the local one*."""
    assert tsubasa.__version__, u"no __version__"
    assert not tsubasa.__version__.startswith(u"0.0.0"), (
        u"__version__ is %r — the placeholder. A release needs a real one."
        % tsubasa.__version__)


# ===========================================================================
# ⭐ THE EMBEDDING CONTRACT — what an application integrating this relies on
# ===========================================================================

def test_an_application_can_point_tsubasa_at_ITS_OWN_ffmpeg(tmp_path):
    u"""⭐ FOR A HOST THAT ALREADY BUNDLES ffmpeg.

        import tsubasa
        tsubasa.set_ffmpeg(my_app_dir / "vendor" / "ffmpeg")

    ⛔ AND IT BEATS `PATH`, WHICH IS THE ENTIRE POINT. `10-deployment.md` puts
    PATH first, which is right for a person who installed ffmpeg once. It is
    WRONG for an application that shipped a specific build and tested against
    it: some unrelated ffmpeg earlier on PATH would silently win.
    """
    from tsubasa.container import ffmpeg as FF

    vendor = tmp_path / u"vendor"
    vendor.mkdir()
    exe = u".exe" if sys.platform == u"win32" else u""
    for tool in (u"ffmpeg", u"ffprobe"):
        (vendor / (tool + exe)).write_bytes(b"#!/bin/sh\n")

    before = FF.location()
    try:
        FF.set_location(str(vendor))
        assert FF.location() == str(vendor)
        for tool in (u"ffmpeg", u"ffprobe"):
            got = FF.find(tool)
            assert got and os.path.dirname(got) == str(vendor), (
                u"%s resolved to %r, not the vendored copy" % (tool, got))
    finally:
        FF.set_location(before)


def test_the_override_accepts_a_DIRECTORY_or_either_BINARY(tmp_path):
    u"""⚠ An embedder may hand us either, and naming `ffmpeg` while we want
    `ffprobe` must find the sibling rather than run one as the other."""
    from tsubasa.container import ffmpeg as FF

    vendor = tmp_path / u"bin"
    vendor.mkdir()
    exe = u".exe" if sys.platform == u"win32" else u""
    for tool in (u"ffmpeg", u"ffprobe"):
        (vendor / (tool + exe)).write_bytes(b"#!/bin/sh\n")

    before = FF.location()
    try:
        for given in (vendor, vendor / (u"ffmpeg" + exe),
                      vendor / (u"ffprobe" + exe)):
            FF.set_location(str(given))
            assert os.path.basename(FF.find(u"ffprobe")).startswith(u"ffprobe")
            assert os.path.basename(FF.find(u"ffmpeg")).startswith(u"ffmpeg")
    finally:
        FF.set_location(before)


def test_clearing_the_override_restores_the_ordinary_search(tmp_path):
    u"""⛔ `set_ffmpeg(None)` must give the search back, not wedge it."""
    from tsubasa.container import ffmpeg as FF
    before = FF.location()
    try:
        FF.set_location(str(tmp_path / u"nowhere"))
        FF.set_location(None)
        assert FF.location() is None
        # ⚠ Asserted as "does not raise and agrees with the plain search",
        # never as "finds something" -- ffmpeg is genuinely optional and a
        # machine without it must still answer this question.
        assert FF.find(u"ffprobe") == FF.find(u"ffprobe")
    finally:
        FF.set_location(before)


def test_set_ffmpeg_is_reachable_from_the_PACKAGE(tmp_path):
    u"""⚠ An embedder should not have to reach into a submodule for the one
    call they need. `doctrine/architecture`: the same reason
    `make_process_dpi_aware` had to come up to the gui package."""
    import tsubasa
    from tsubasa.container import ffmpeg as FF
    assert tsubasa.set_ffmpeg is FF.set_location
    assert u"set_ffmpeg" in tsubasa.__all__
